const body = document.querySelector('body'),
    header = document.querySelector('header'),
    navWrapper = document.querySelector('.header__nav-wrapper'),
    mainSectionNav = document.getElementById('mainSectionNav'),
    mainSection = document.getElementById('mainSection'),
    warehousesSectionNav = document.getElementById('warehousesSectionNav'),
    warehousesSection = document.getElementById('findWarehouseSection'),
    aboutUsSectionNav = document.getElementById('aboutUsSectionNav'),
    aboutUsSection = document.getElementById('aboutUsSection'),
    contactsSectionNav = document.getElementById('contactsSectionNav'),
    contactsSection = document.getElementById('contactsSection'),
    addWarehouseSectionNav = document.getElementById('addWarehouseSectionNav'),
    addWarehouseSection = document.getElementById('addWarehouseSection'),
    addWarehouseForm = document.getElementById('addWarehouseForm'),
    addWarehouseFormSubmit = document.getElementById('addWarehouseFormSubmit'),
    addWarehouseFormEmail = document.getElementById('addWarehouseFormEmail'),
    addWarehouseFormName = document.getElementById('addWarehouseFormName'),
    addWarehouseFormWarehouseName = document.getElementById('addWarehouseFormWarehouseName'),
    addWarehouseFormWarehouseAddress = document.getElementById('addWarehouseFormWarehouseAddress'),
    addWarehouseFormComment = document.getElementById('addWarehouseFormComment'),
    findWarehouseSwitchLeft = document.getElementById('findWarehouseSwitchLeft'),
    findWarehouseSwitchRight = document.getElementById('findWarehouseSwitchRight'),
    findWarehouseFilterButton = document.getElementById('findWarehouseFilterButton'),
    findWarehouseFilterForm = document.getElementById('findWarehouseFilterForm'),
    findWarehouseView = document.getElementById('findWarehouseView'),
    warehouseDetailsModalDialog = document.getElementById('warehouseDetailsDialog');

export { body, header, navWrapper, mainSectionNav, mainSection, warehousesSectionNav, warehousesSection, aboutUsSectionNav, aboutUsSection, 
    contactsSectionNav, contactsSection, addWarehouseSectionNav, addWarehouseSection, addWarehouseForm, addWarehouseFormSubmit, 
    addWarehouseFormEmail, addWarehouseFormName, addWarehouseFormWarehouseName, addWarehouseFormWarehouseAddress, addWarehouseFormComment, 
    findWarehouseSwitchLeft, findWarehouseSwitchRight, findWarehouseFilterButton, findWarehouseFilterForm, findWarehouseView,
    warehouseDetailsModalDialog }